### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by kogetsukenji** [pawadski/curlhttp_exporter#7]
Can we have proxy option please ?

**Comment by pawadski** [comment]
You can use a proxy like this (I tested using a http proxy) inside config.yml:

```
curl_settings:
  proxy: '123.123.123.123'
  proxyport: 8080
  proxytype: proxytype_http
```
